### ISSUE TITLE
System.NullReferenceException when call method with nullable arguments on version 3.0.0-beta-2038

### ISSUE THREAD

**Issue by lamnbp** [sebastienros/jint#1208]
**I'm using version 3.0.0-beta-2038:**

```
using Jint;		
public class Program
{
	public static void Main()
	{
		Engine _engine = new Engine().SetValue("JintCommon", new JintCommon());
                Engine _runner = _engine.Execute("JintCommon.sum(1, null)");
	}
	
	public class JintCommon{
		public int sum(int a, int? b){
			return a + (b.GetValueOrDefault(1));
		}
	}
}
```

**Fiddle:** https://dotnetfiddle.net/4Ns67P

**Exception:**

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Jint.Runtime.TypeConverter.IsAssignableToGenericType(Type givenType, Type genericType)
   at Jint.Runtime.Interop.MethodInfoFunctionInstance.IsGenericParameter(Object argObj, Type parameterType, Int32 parameterIndex)
   at Jint.Runtime.Interop.MethodInfoFunctionInstance.Call(JsValue thisObject, JsValue[] jsArguments)
   at Jint.Engine.Call(FunctionInstance functionInstance, JsValue thisObject, JsValue[] arguments, JintExpression expression)
   at Jint.Engine.Call(ICallable callable, JsValue thisObject, JsValue[] arguments, JintExpression expression)
   at Jint.Runtime.Interpreter.Expressions.JintCallExpression.EvaluateCall(EvaluationContext context, JsValue func, Object reference, NodeList`1& arguments, Boolean tailPosition)
   at Jint.Runtime.Interpreter.Expressions.JintCallExpression.Call(EvaluationContext context)
   at Jint.Runtime.Interpreter.Expressions.JintCallExpression.EvaluateInternal(EvaluationContext context)
   at Jint.Runtime.Interpreter.Statements.JintExpressionStatement.ExecuteInternal(EvaluationContext context)
   at Jint.Runtime.Interpreter.JintStatementList.Execute(EvaluationContext context)
   at Jint.Engine.<>c__DisplayClass63_0.<Execute>g__DoInvoke|0()
   at Jint.Engine.ExecuteWithConstraints[T](Boolean strict, Func`1 callback)
   at Jint.Engine.Execute(Script script)
   at Jint.Engine.Execute(String source, ParserOptions parserOptions)
   at Jint.Engine.Execute(String source)
   at Program.Main()
Command terminated by signal 6
```

Occurred only on version 3.0.0-beta-2038. Still works fine on version 3.0.0-beta-2037.

**Comment by EternalQuasar0206** [comment]
Apparently this is happening only in internal code.

Example using MelonRuntime (uses Jint):

<details>

![image](https://user-images.githubusercontent.com/70824102/176352962-454d8f88-be1e-43d7-944a-72ebf877c868.png)

</details>

MelonConsole (bind to `console.log`) implementation:

```cs
public static void Write(object obj, int color)
{
    try
    {
        JsonSerializerOptions options = new()
        {
            ReferenceHandler = ReferenceHandler.IgnoreCycles,
            WriteIndented = true
        };

        var serialized = JsonSerializer.Serialize(obj, options);
        CLNConsole.Write(serialized, color);
    }
    catch
    {
        CLNConsole.Write(obj.GetType().ToString(), color);
    }

    Console.WriteLine();
}
```

**Comment by lahma** [comment]
Thanks for the report, should be fixed in main now.
