### ISSUE TITLE
JavaScriptErrorWrapperException SetCallstack throws argument exception

### ISSUE THREAD

**Issue by RaidMax** [sebastienros/jint#1320]
`SetCallstack` in `JavaScriptErrorWrapperException` throws an argument exception when trying to convert the stack to a string instead of properly bubbling up the JavascriptException. 
This seems to happen when the stack trace is essentially empty eg when the code executing is at a top level javascript function.

This issue is in 3.0.0-beta-2041 and was introduced sometime after 2038. Most likely in this commit:
https://github.com/sebastienros/jint/blame/2b58d122e73a00af1149e14a6a289cf510536f80/Jint/Runtime/JavaScriptException.cs#L98

`errObj.Get(CommonProperties.Stack)` returns undefined;

Type: **ArgumentException**
Message: **Expected string but got Undefined**
Stack Trace:  
```at Jint.Runtime.ExceptionHelper.ThrowArgumentException(String message, String paramName)
   at Jint.Runtime.ExceptionHelper.ThrowArgumentException(String message)
   at Jint.JsValueExtensions.ThrowWrongTypeException(JsValue value, String expectedType)
   at Jint.Runtime.JavaScriptException.JavaScriptErrorWrapperException.SetCallstack(Engine engine, Location location, Boolean overwriteExisting)
   at Jint.Runtime.JavaScriptException.SetJavaScriptCallstack(Engine engine, Location& location, Boolean overwriteExisting)
   at Jint.Runtime.ExceptionHelper.ThrowJavaScriptException(Engine engine, JsValue value, Completion& result)
   at Jint.Native.Function.ScriptFunctionInstance.Call(JsValue thisArgument, JsValue[] arguments)
   at Jint.Runtime.Interpreter.Expressions.JintCallExpression.EvaluateInternal(EvaluationContext context)
   at Jint.Runtime.Interpreter.Expressions.JintExpression.GetValue(EvaluationContext context)
   at Jint.Runtime.Interpreter.Statements.JintVariableDeclaration.ExecuteInternal(EvaluationContext context)
   at Jint.Runtime.Interpreter.JintStatementList.Execute(EvaluationContext context)
```

Might be difficult to provide a repro since this occurs when I pass a delegate javascript function back to C# and then invoke it from C#

**Comment by lahma** [comment]
I think we would need a unit test to show the problem in order to correctly fix and ensure that it won't happen accidentally again.

**Comment by RaidMax** [comment]
> I think we would need a unit test to show the problem in order to correctly fix and ensure that it won't happen accidentally again.

I was able to simplify a repro 


```csharp
using Jint;
using Jint.Native;

Delegate? func = null;
void SetFuncValue(Delegate scriptFunc) => func = scriptFunc; 

var engine = new Engine();
engine.SetValue("SetFuncValue", SetFuncValue);
engine.Evaluate("SetFuncValue(() => { foo.bar });");

var funcArgs = Array.Empty<object>().Select(p => JsValue.FromObject(engine, p)).ToArray();
func?.DynamicInvoke(JsValue.Undefined, funcArgs);
```

Expected behavior: JavaScriptException is thrown with line/trace details
Observed behavior: ArgumentException is thrown and JavaScript engine state data is lost

Removing `foo.bar` or writing any valid JS code will execute without issue.
