### ISSUE TITLE
`parseFloat` fails on large values

### ISSUE THREAD

**Issue by DSchroer** [sebastienros/jint#1395]
If you try to run `parseFloat` on large values (AKA MAX_INTEGER). Jint throws an exception as it overflows the decimal value being used within the parse method.

## Example:
```js
parseFloat('1.7976931348623157e+308');
```

## Stack:
```
System.OverflowException
Value was either too large or too small for a Decimal.
   at System.Number.ThrowOverflowException(TypeCode type)
   at System.Decimal.DecCalc.ScaleResult(Buf24* bufRes, UInt32 hiRes, Int32 scale)
   at System.Decimal.DecCalc.VarDecMul(DecCalc& d1, DecCalc& d2)
   at System.Decimal.op_Multiply(Decimal d1, Decimal d2)
   at Jint.Native.Global.GlobalObject.ParseFloat(JsValue thisObject, JsValue[] arguments) in /Users/dominick.schroer/Projects/jint/Jint/Native/Global/GlobalObject.cs:line 366
```

**Comment by lahma** [comment]
Thanks for the report, should be fixed now in main and soon available on MyGet feed.

**Comment by camiteca** [comment]
Hi guys, i've encountered the same issue and was wondering if this is going to be released in 2.x. We've updated to the prerelease nuget (3.x) and the issue seems to be solved, but it's still a prerelease. Any thoughts?
