### ISSUE TITLE
JsArray.GetOwnProperties throws ArrayTypeMismatchException

### ISSUE THREAD

**Issue by tkovacs-dev** [sebastienros/jint#1419]
Run the following code:
`new JsArray(new Engine(), new JsValue[] { 1 }).GetOwnProperties().ToArray();`

This throws the following exception:
``System.ArrayTypeMismatchException: Attempted to access an element as a type incompatible with the array.
   at Jint.Native.Array.ArrayInstance.GetOwnProperties()+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at JintCrashRepro.Program.Main(String[] args) in C:\Users\tkovacs\source\repos\JintCrashRepro\Program.cs:line 12``

What I expected is to get two `PropertyDescriptor`s, one for the index 0 and one for `length`.

The jint version is 3.0.0-beta-2046

**Comment by lahma** [comment]
Thanks for the report, should now be fixed in main / soon available on MyGet feed.
