### ISSUE TITLE
When trying to automatically convert object into string, an exception is thrown.

### ISSUE THREAD

**Issue by david-w-lee** [sebastienros/jint#1467]
When I run this code, the following exception is thrown.
If you comment out indexer in MyClass, this code runs fine.

    public class MyClass
    {
        public string MyProp
        {
            get { return "from property"; }
        }

        public string this[string propname]
        {
            get { return "from indexer"; }
        }
    }

    public class Program
    {
        public static void Main()
        {
            var engine = new Engine();
            engine.SetValue("myobj", new MyClass());
            engine.SetValue("debug", new Action<string>(Console.WriteLine));
            var res = engine.Evaluate("debug(\"MyClass: \" + myobj)");
            Console.ReadKey();
        }
    }

Unhandled exception. Jint.Runtime.JavaScriptException: Value returned for property 'Symbol(Symbol.toPrimitive)' of object is not a function
 ---> Error: Value returned for property 'Symbol(Symbol.toPrimitive)' of object is not a function
   at <anonymous>:1:21
   --- End of inner exception stack trace ---
   at Jint.Engine.ScriptEvaluation(ScriptRecord scriptRecord) in C:\projects\jint_test\Jint\Engine.cs:line 328
   at Jint.Engine.<>c__DisplayClass71_0.<Execute>b__0() in C:\projects\jint_test\Jint\Engine.cs:line 285
   at Jint.Engine.ExecuteWithConstraints[T](Boolean strict, Func`1 callback) in C:\projects\jint_test\Jint\Engine.cs:line 673
   at Jint.Engine.Execute(Script script) in C:\projects\jint_test\Jint\Engine.cs:line 285
   at Jint.Engine.Evaluate(Script script) in C:\projects\jint_test\Jint\Engine.cs:line 263
   at Jint.Engine.Evaluate(String code, String source, ParserOptions parserOptions) in C:\projects\jint_test\Jint\Engine.cs:line 259
   at Jint.Engine.Evaluate(String code) in C:\projects\jint_test\Jint\Engine.cs:line 243
   at JintTest.Program.Main() in C:\projects\jint_test\JintTest\Program.cs:line 31

**Comment by lahma** [comment]
Would you like to help out with a PR?

**Comment by david-w-lee** [comment]
I am not sure if this is a proper fix but I think I should add the following lines in ObjectWrapper.cs public override PropertyDescriptor GetOwnProperty(JsValue property)
![image](https://user-images.githubusercontent.com/33561818/221188812-193ac92a-0e10-4281-85c2-4dda71ce4f1c.png)

**Comment by lahma** [comment]
Should now be fixed in main and soon available on MyGet.
