### ISSUE TITLE
Unable to use a Value of JsonNode having Array

### ISSUE THREAD

**Issue by jaliyaudagedara** [sebastienros/jint#1636]
**Version used**: 3.0.0-beta-2051

**Describe the bug**

Consider the following example.

```csharp
var variables = JsonNode.Parse("""
    {
        "employees": {
            "type": "array",
            "value": [
                {
                    "firstName": "John",
                    "lastName": "Doe"
                },
                {
                    "firstName": "Jane",
                    "lastName": "Doe"
                }
            ]
        }
    }
    """);

var engine = new Engine()
    .SetValue("log", new Action<object>(Console.WriteLine))
    .SetValue("variables", variables)
    .Execute("""
        function populateFullName() {
            log(variables['employees']['value']);

            return variables['employees'].value.map(function (item) {
                log(item);

                var newItem = 
                {
                    "firstName": item.firstName,
                    "lastName": item.lastName,
                    "fullName": item.firstName + ' ' + item.lastName
                };

                return newItem;
            });
        }   
    """);

var result = engine .Invoke("populateFullName").ToObject();
```

**Output**:
Note: the `log` statement. It shows it's an array.
```
[
  {
    "firstName": "John",
    "lastName": "Doe"
  },
  {
    "firstName": "Jane",
    "lastName": "Doe"
  }
]
Unhandled exception. System.InvalidOperationException: The node must be of type 'JsonObject'.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_NodeWrongType(String typeName)
   at System.Text.Json.Nodes.JsonNode.AsObject()
   at System.Text.Json.Nodes.JsonNode.get_Item(String propertyName)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
--- End of stack trace from previous location ---
   at Jint.Runtime.ExceptionHelper.ThrowMeaningfulException(Engine engine, TargetInvocationException exception)
   at Jint.Runtime.Interop.Reflection.ReflectionAccessor.GetValue(Engine engine, Object target)
   at Jint.Runtime.Descriptors.Specialized.ReflectionDescriptor.get_CustomValue()
   at Jint.Native.Object.ObjectInstance.UnwrapJsValue(PropertyDescriptor desc, JsValue thisObject)
   at Jint.Native.Object.ObjectInstance.Get(JsValue property, JsValue receiver)
   at Jint.Runtime.Interop.ObjectWrapper.Get(JsValue property, JsValue receiver)
   at Jint.Engine.GetValue(Reference reference, Boolean returnReferenceToPool)
   at Jint.Engine.GetValue(Object value, Boolean returnReferenceToPool)
   at Jint.Runtime.Interpreter.Expressions.JintCallExpression.EvaluateInternal(EvaluationContext context)
   at Jint.Runtime.Interpreter.Expressions.JintExpression.GetValue(EvaluationContext context)
   at Jint.Runtime.Interpreter.Statements.JintReturnStatement.ExecuteInternal(EvaluationContext context)
   at Jint.Runtime.Interpreter.JintStatementList.Execute(EvaluationContext context)
   at Jint.Native.Function.ScriptFunctionInstance.Call(JsValue thisArgument, JsValue[] arguments)
   at Jint.Native.Function.FunctionInstance.Jint.Native.ICallable.Call(JsValue thisObject, JsValue[] arguments)
   at Jint.Engine.<>c__DisplayClass98_0.<Invoke>g__DoInvoke|0()
   at Jint.Engine.ExecuteWithConstraints[T](Boolean strict, Func`1 callback)
   at Jint.Engine.Invoke(JsValue value, Object thisObj, Object[] arguments)
   at Jint.Engine.Invoke(String propertyName, Object thisObj, Object[] arguments)
   at Jint.Engine.Invoke(String propertyName, Object[] arguments)
```
**Expected behavior**

The value of `result` should be a `JsonArray`.

**Comment by viruscamp** [comment]
`variables['employees'].value` is a `JsonArray`, a `ICollection<JsonNode>` and also a `JsonNode`.   
Currently, we donot attach array-like functions like `map` to any `ICollection<T>`,  so it fall back to `JsonNode["map"]`.  
This feature is under disscusion, see https://github.com/sebastienros/jint/discussions/1618

**Comment by lahma** [comment]
Created a sample for some STJ access: https://github.com/sebastienros/jint/pull/1663 , you can submit PRs to extend and improve the sample to show how to work around different oddities of STJ.
