### ISSUE TITLE
'Property 'Wait' of object is not a function' when calling .Wait() on a task with the usage of Jint 3.0.1

### ISSUE THREAD

**Issue by arekpalinski** [sebastienros/jint#1812]
**Version used**

3.0.1

**Describe the bug**

We get the following exception in RavenDB with the usage of Jint 3.0.1:

```
Raven.Client.Exceptions.Documents.Patching.JavaScriptException: At 0:3 Script failed for document ID ''. {"message":"Property 'Wait' of object is not a function","stack":"   at execute (server, database) :3:1\r\n   at :5:1"}
 ---> Jint.Runtime.JavaScriptException: Property 'Wait' of object is not a function
 ---> Error: Property 'Wait' of object is not a function
   at execute (server, database) :3:1
   at :5:1
   --- End of inner exception stack trace ---
   at Jint.Runtime.ExceptionHelper.ThrowJavaScriptException(Engine engine, JsValue value, Completion& result)
   at Jint.Native.Function.ScriptFunction.Call(JsValue thisObject, JsValue[] arguments)
   at Jint.Engine.Call(Function function, JsValue thisObject, JsValue[] arguments, JintExpression expression)
   at Jint.Engine.<>c__DisplayClass133_0.<Call>g__Callback|0()
   at Jint.Engine.ExecuteWithConstraints[T](Boolean strict, Func`1 callback)
   at Jint.Engine.Call(JsValue callable, JsValue thisObject, JsValue[] arguments)
   at Raven.Server.Documents.Patch.ScriptRunner.SingleRun.Run(JsonOperationContext jsonCtx, DocumentsOperationContext docCtx, String method, String documentId, Object[] args, QueryTimingsScope scope, CancellationToken token) in D:\workspace\ravendb-6.0\src\Raven.Server\Documents\Patch\ScriptRunner.cs:line 2114
   --- End of inner exception stack trace ---
   at Raven.Server.Documents.Patch.ScriptRunner.SingleRun.Run(JsonOperationContext jsonCtx, DocumentsOperationContext docCtx, String method, String documentId, Object[] args, QueryTimingsScope scope, CancellationToken token) in D:\workspace\ravendb-6.0\src\Raven.Server\Documents\Patch\ScriptRunner.cs:line 2129
   at Raven.Server.Documents.Patch.ScriptRunner.SingleRun.Run(JsonOperationContext jsonCtx, DocumentsOperationContext docCtx, String method, Object[] args, QueryTimingsScope scope, CancellationToken token) in D:\workspace\ravendb-6.0\src\Raven.Server\Documents\Patch\ScriptRunner.cs:line 2093
   at Raven.Server.Documents.Patch.AdminJsConsole.ApplyScript(AdminJsScript script) in D:\workspace\ravendb-6.0\src\Raven.Server\Documents\Patch\AdminJsConsole.cs:line 44
   at Raven.Server.Web.System.AdminDatabasesHandler.AdminConsole() in D:\workspace\ravendb-6.0\src\Raven.Server\Web\System\AdminDatabasesHandler.cs:line 1017
   at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in D:\workspace\ravendb-6.0\src\Raven.Server\Routing\RequestRouter.cs:line 418
   at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in D:\workspace\ravendb-6.0\src\Raven.Server\RavenServerStartup.cs:line 192
```

We have verified it was not happening on 3.0.0

**To Reproduce**

Run the following code:

```
server.ServerStore.EnsureNotPassiveAsync(null, "A").Wait();
```

in RavenDB's Admin JS Console (https://ravendb.net/docs/article-page/6.0/csharp/studio/server/debug/admin-js-console).

`EnsureNotPassiveAsync()` returns  C# `Task` object.
 
**Expected behavior**

No Exception

**Additional context**

This is happening in RavenDB Server CC @lahma

**Comment by arekpalinski** [comment]
Maybe related to https://github.com/sebastienros/jint/pull/1787?

**Comment by ml054** [comment]
Please also check Result property on task as stated here https://github.com/sebastienros/jint/pull/1787#issuecomment-1974799496

Thanks :)

**Comment by arekpalinski** [comment]
Hi, any update here?

**Comment by lahma** [comment]
Well current update is that we are being pinged by a commercial product for free work 🤷🏻‍♂️ 

Is the calling code owned by you? I think having `await` for the task would resolve the issue. Not sure if the Task to Promise conversion should be more explicit.

**Comment by arekpalinski** [comment]
Marko, don't get me wrong. I decided to ping here since at glance it looked as a regression issue from our perspective so I thought it might be important. There was no response so I thought it could get lost somehow or maybe you already checked it and know something more but didn't update here.

Regarding the actual issue, simply converting the sample script from:

```
server.ServerStore.EnsureNotPassiveAsync(null, "A").Wait();
```

to

```
await server.ServerStore.EnsureNotPassiveAsync(null, "A");
```

doesn't work for us but this is because the function that we wrap the script provided by a user (like the above) isn't declared as `async`:

https://github.com/ravendb/ravendb/blob/0ddbe3215a3e6d4814758f9bb4211d3cb9a6f93b/src/Raven.Server/Documents/Patch/AdminJsConsole.cs#L105-L109

```
runner.AddScript($@"function execute(server, database){{ 

{_script}

}};");
```

If we change it to:

```
async function execute(server, database){{ 

{_script}

}};
```

then the call `await server.ServerStore.EnsureNotPassiveAsync(null, "A");` works as expected (our tests checking JS Admin Console feature fail then but this is because now `execute` function returns `JsPromise` instead of `JsValue` so I guess we'll need to use `UnwrapIfPromise()`).

Do you think that's the way to go for us? We have reverted to Jint 3.0.0 for now but we'd like to do the update it in the next release.
