### ISSUE TITLE
Setting private properties causes NRE

### ISSUE THREAD

**Issue by VelvetToroyashi** [sebastienros/jint#1921]
**Version used**

Jint 3.1.5

**Describe the bug**

Setting a [private property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_properties) on a class in any capacity throws a NullReferenceException from native code.

**To Reproduce**

```js
class ClassWithPrivateField {
    #nonexistent = 'evidently';
}

new ClassWithPrivateField().#nonexistent = 'explosion!';
```

**Expected behavior**

Jint throws a managed (JavaScript) exception as it does with attempting to use other invalid properties.

**Additional context**

This specifically occurs when attempting to set a private property outside of a class (e.g., in a module function). Interestingly, doing it in a class function throws a different (and equally as vague) exception (though, "not found" does seem more indicative of correct behavior here-):

```fix
Promise was rejected with value ReferenceError: TODO Not found!!
Stack trace: 
   at Bot (eventCallback, commandCallback) bootstrap:34:23
   at entrypoint () bootstrap:15:21
   at bootstrap:23:8



```

**Comment by lahma** [comment]
So iare there more code sample of specific cases? Ideally in c# utilizing the Engine.

**Comment by VelvetToroyashi** [comment]
@lahma Here's a minimal repro in .NET:
```cs
using Jint;

var engine = new Engine
(
    opt =>
    {
        opt.Strict();
    }
);

engine.Evaluate
(
    """
    class A { }
    
    new A().#nonexistent = 1;
    """
);
```

And the produced exception:

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Jint.Runtime.Interpreter.Expressions.JintPrivateIdentifierExpression.EvaluateInternal(EvaluationContext context)
   at Jint.Runtime.Interpreter.Expressions.JintExpression.GetValue(EvaluationContext context)
   at Jint.Runtime.Interpreter.Expressions.JintMemberExpression.EvaluateInternal(EvaluationContext context)
   at Jint.Runtime.Interpreter.Expressions.JintAssignmentExpression.SimpleAssignmentExpression.SetValue(EvaluationContext context)
   at Jint.Runtime.Interpreter.Expressions.JintAssignmentExpression.SimpleAssignmentExpression.EvaluateInternal(EvaluationContext context)
   at Jint.Runtime.Interpreter.Expressions.JintExpression.GetValue(EvaluationContext context)
   at Jint.Runtime.Interpreter.Statements.JintExpressionStatement.ExecuteInternal(EvaluationContext context)
   at Jint.Engine.ScriptEvaluation(ScriptRecord scriptRecord, ParserOptions parserOptions)
   at Jint.Engine.<>c__DisplayClass96_0.<Execute>b__0()
   at Jint.Engine.ExecuteWithConstraints[T](Boolean strict, Func`1 callback)
   at Jint.Engine.Execute(Prepared`1& preparedScript)
   at Jint.Engine.Evaluate(Prepared`1& preparedScript)

```

**Comment by lahma** [comment]
Thanks, what about the different error message in different call context?

**Comment by VelvetToroyashi** [comment]
```js
class A { 
    constructor() { #nonexistent = 2; }
}
new A();
```

Produces the following JS error:

```
class A { 
    constructor() { #nonexistent = 2; }
}
new A();
```

**Comment by lahma** [comment]
Thanks for the repros. Now far easier to investigate 👍🏻

**Comment by lahma** [comment]
This was a bit monkey-patched as in v4 the parser actually detects these errors better instead of allowing the code to get into Jint's runtime logic. But at least the error message should now be better.
