### ISSUE TITLE
JSON.stringify fails on a Dictionary<string, object> instance

### ISSUE THREAD

**Issue by doronguttman** [sebastienros/jint#216]
Here's a unit test:

```
_engine.SetValue("dict", new Dictionary<string, object> { {"foo", "bar"}, {"bar", "foo"} });
Assert.DoesNotThrows(() => RunTest("JSON.stringify(dict);"));
```

FYI, exception thrown:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Jint.Runtime.Descriptors.Specialized.IndexDescriptor.get_Value() in c:\code\jint\Jint\Runtime\Descriptors\Specialized\IndexDescriptor.cs:line 33
   at Jint.Native.Object.ObjectInstance.Get(String propertyName) in c:\code\jint\Jint\Native\Object\ObjectInstance.cs:line 58
   at Jint.Native.Json.JsonSerializer.Str(String key, ObjectInstance holder) in c:\code\jint\Jint\Native\Json\JsonSerializer.cs:line 127
   at Jint.Native.Json.JsonSerializer.Serialize(JsValue value, JsValue replacer, JsValue space) in c:\code\jint\Jint\Native\Json\JsonSerializer.cs:line 118
   at Jint.Native.Json.JsonInstance.Stringify(JsValue thisObject, JsValue[] arguments) in c:\code\jint\Jint\Native\Json\JsonInstance.cs:line 72
   at Jint.Runtime.Interop.ClrFunctionInstance.Call(JsValue thisObject, JsValue[] arguments) in c:\code\jint\Jint\Runtime\Interop\ClrFunctionInstance.cs:line 31
   at Jint.Runtime.ExpressionInterpreter.EvaluateCallExpression(CallExpression callExpression) in c:\code\jint\Jint\Runtime\ExpressionIntepreter.cs:line 840
   at Jint.Engine.EvaluateExpression(Expression expression) in c:\code\jint\Jint\Engine.cs:line 358
   at Jint.Runtime.ExpressionInterpreter.EvaluateExpression(Expression expression) in c:\code\jint\Jint\Runtime\ExpressionIntepreter.cs:line 24
   at System.Linq.Enumerable.<>c__DisplayClass12`3.<CombineSelectors>b__11(TSource x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Jint.Runtime.ExpressionInterpreter.EvaluateCallExpression(CallExpression callExpression) in c:\code\jint\Jint\Runtime\ExpressionIntepreter.cs:line 795
   at Jint.Engine.EvaluateExpression(Expression expression) in c:\code\jint\Jint\Engine.cs:line 358
   at Jint.Runtime.StatementInterpreter.ExecuteExpressionStatement(ExpressionStatement expressionStatement) in c:\code\jint\Jint\Runtime\StatementInterpreter.cs:line 32
   at Jint.Engine.ExecuteStatement(Statement statement) in c:\code\jint\Jint\Engine.cs:line 296
   at Jint.Runtime.StatementInterpreter.ExecuteStatement(Statement statement) in c:\code\jint\Jint\Runtime\StatementInterpreter.cs:line 22
   at Jint.Runtime.StatementInterpreter.ExecuteStatementList(IEnumerable`1 statementList) in c:\code\jint\Jint\Runtime\StatementInterpreter.cs:line 417
   at Jint.Runtime.StatementInterpreter.ExecuteProgram(Program program) in c:\code\jint\Jint\Runtime\StatementInterpreter.cs:line 488
   at Jint.Engine.Execute(Program program) in c:\code\jint\Jint\Engine.cs:line 240
```

**Comment by doronguttman** [comment]
popping up

**Comment by lahma** [comment]
Checked and also this was resolved by https://github.com/sebastienros/jint/pull/750
