### ISSUE TITLE
Calling Object.keys() trows an InvalidCastException

### ISSUE THREAD

**Issue by T917820981726** [sebastienros/jint#229]
Hi,
I'm trying to run the following Javascript code in Jint (Object.keys(O) as defined in [ECMAScript 5.1, 15.2.3.14](http://www.ecma-international.org/ecma-262/5.1/#sec-15.2.3.14)):
```javascript
var o = {
    a: 'A',
    b: 'B'
};

var oKeys = Object.keys(o);
log(oKeys);
```

On Firefox, IE and Chrome this outputs something like
```javascript
["a", "b"]
```
(an array containing the two keys of the specified object.

However, when running this in Jint, I get the following Exception in .Net:
```
System.InvalidCastException: Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Jint.Runtime.Interop.DefaultTypeConverter.Convert(Object value, Type type, IFormatProvider formatProvider) in C:\Users\VPC\Desktop\jint\Jint\Runtime\Interop\DefaultTypeConverter.cs:line 173
   at Jint.Runtime.Interop.DelegateWrapper.Call(JsValue thisObject, JsValue[] jsArguments) in C:\Users\VPC\Desktop\jint\Jint\Runtime\Interop\DelegateWrapper.cs:line 46
   at Jint.Runtime.ExpressionInterpreter.EvaluateCallExpression(CallExpression callExpression) in C:\Users\VPC\Desktop\jint\Jint\Runtime\ExpressionIntepreter.cs:line 858
   at Jint.Engine.EvaluateExpression(Expression expression) in C:\Users\VPC\Desktop\jint\Jint\Engine.cs:line 426
   at Jint.Runtime.StatementInterpreter.ExecuteExpressionStatement(ExpressionStatement expressionStatement) in C:\Users\VPC\Desktop\jint\Jint\Runtime\StatementInterpreter.cs:line 32
   at Jint.Engine.ExecuteStatement(Statement statement) in C:\Users\VPC\Desktop\jint\Jint\Engine.cs:line 364
   at Jint.Runtime.StatementInterpreter.ExecuteStatement(Statement statement) in C:\Users\VPC\Desktop\jint\Jint\Runtime\StatementInterpreter.cs:line 22
   at Jint.Runtime.StatementInterpreter.ExecuteStatementList(IEnumerable`1 statementList) in C:\Users\VPC\Desktop\jint\Jint\Runtime\StatementInterpreter.cs:line 420
   at Jint.Runtime.StatementInterpreter.ExecuteProgram(Program program) in C:\Users\VPC\Desktop\jint\Jint\Runtime\StatementInterpreter.cs:line 498
   at Jint.Engine.Execute(Program program) in C:\Users\VPC\Desktop\jint\Jint\Engine.cs:line 295
   at ConsoleApplication1.Program.<>c.<Main>b__1_0() in C:\Users\VPC\Desktop\jint\ConsoleApplication1\Program.cs:line 82
```

Note that I try to run Object.keys() on a plain JavaScript object, not on an external .Net object. Am I doing something wrong?
Thanks!

**Comment by T917820981726** [comment]
Sorry, I just realized the issue was with the log() method, not with Object.keys() - it works correctly.
