### ISSUE TITLE
Date.prototype.toDateString(), .toString() etc. generate a .Net Exception (NRE) instead of throwing a javascript exception on incompatible object

### ISSUE THREAD

**Issue by T917820981726** [sebastienros/jint#231]
Hi,
I'm trying the following javascript code:
```javascript
try {
    var myObj = Object.create(Date.prototype);
    myObj.toDateString();
} catch (e) {
    'Catched JS Exception: ' + e;
}
```
On IE, Firefox, Chrome and Nashorn (Java JS engine) this shows something like:
```
"Catched JS Exception: TypeError: toDateString method called on incompatible Object"
```
So a TypeError is thrown that can be catched in the javascript.

However, in Jint this leads to an NullReferenceException being thrown, making the javascript unable to catch it:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jint.Native.Date.DatePrototype.ToDateString(JsValue thisObj, JsValue[] arguments) in C:\Users\VPC\Desktop\jint\Jint\Native\Date\DatePrototype.cs:line 93
   at Jint.Runtime.Interop.ClrFunctionInstance.Call(JsValue thisObject, JsValue[] arguments) in C:\Users\VPC\Desktop\jint\Jint\Runtime\Interop\ClrFunctionInstance.cs:line 32
   at Jint.Runtime.ExpressionInterpreter.EvaluateCallExpression(CallExpression callExpression) in C:\Users\VPC\Desktop\jint\Jint\Runtime\ExpressionIntepreter.cs:line 858
   at Jint.Engine.EvaluateExpression(Expression expression) in C:\Users\VPC\Desktop\jint\Jint\Engine.cs:line 426
   at Jint.Runtime.StatementInterpreter.ExecuteExpressionStatement(ExpressionStatement expressionStatement) in C:\Users\VPC\Desktop\jint\Jint\Runtime\StatementInterpreter.cs:line 32
   at Jint.Engine.ExecuteStatement(Statement statement) in C:\Users\VPC\Desktop\jint\Jint\Engine.cs:line 364
   at Jint.Runtime.StatementInterpreter.ExecuteStatement(Statement statement) in C:\Users\VPC\Desktop\jint\Jint\Runtime\StatementInterpreter.cs:line 22
   at Jint.Runtime.StatementInterpreter.ExecuteStatementList(IEnumerable`1 statementList) in C:\Users\VPC\Desktop\jint\Jint\Runtime\StatementInterpreter.cs:line 420
   at Jint.Runtime.StatementInterpreter.ExecuteBlockStatement(BlockStatement blockStatement) in C:\Users\VPC\Desktop\jint\Jint\Runtime\StatementInterpreter.cs:line 531
   at Jint.Engine.ExecuteStatement(Statement statement) in C:\Users\VPC\Desktop\jint\Jint\Engine.cs:line 346
   at Jint.Runtime.StatementInterpreter.ExecuteStatement(Statement statement) in C:\Users\VPC\Desktop\jint\Jint\Runtime\StatementInterpreter.cs:line 22
   at Jint.Runtime.StatementInterpreter.ExecuteTryStatement(TryStatement tryStatement) in C:\Users\VPC\Desktop\jint\Jint\Runtime\StatementInterpreter.cs:line 462
   at Jint.Engine.ExecuteStatement(Statement statement) in C:\Users\VPC\Desktop\jint\Jint\Engine.cs:line 391
   at Jint.Runtime.StatementInterpreter.ExecuteStatement(Statement statement) in C:\Users\VPC\Desktop\jint\Jint\Runtime\StatementInterpreter.cs:line 22
   at Jint.Runtime.StatementInterpreter.ExecuteStatementList(IEnumerable`1 statementList) in C:\Users\VPC\Desktop\jint\Jint\Runtime\StatementInterpreter.cs:line 420
   at Jint.Runtime.StatementInterpreter.ExecuteProgram(Program program) in C:\Users\VPC\Desktop\jint\Jint\Runtime\StatementInterpreter.cs:line 498
   at Jint.Engine.Execute(Program program) in C:\Users\VPC\Desktop\jint\Jint\Engine.cs:line 295
   at ConsoleApplication1.Program.<>c.<Main>b__1_0() in C:\Users\VPC\Desktop\jint\ConsoleApplication1\Program.cs:line 80
```

This exception also occurs e.g. when calling myObj.toString() (where toString() in Firefox returns "Invalid Date"), myObj.valueOf() etc.

On other object's toString (e.g. Boolean.toString() a TypeError is thrown in Javascript.
Shouldn't a javascript exception (TypeError) also be thrown when running Date.toString() in an incompatible object?

Thanks!

**Comment by sebastienros** [comment]
Per http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.5 you are right. Fixing it.
