### ISSUE TITLE
System.Console.WriteLine(JSON.stringify(...)) does not work 

### ISSUE THREAD

**Issue by nilsmoh** [sebastienros/jint#244]
(was created on codeplex isssue-tracker https://jint.codeplex.com/workitem/6996 but refers to the new implementation)

Hi,
I can use JSON.stringify() and return it's result to C#.
Also I can dump strings with System.Console.WriteLine().
However I cannot combine these two and always get an exception.
Using latest package from nuget.
Any comments, pls?

**Comment by nilsmoh** [comment]
Code to reproduce Exception:
this.engine.Execute("System.Console.WriteLine(JSON.stringify({x:12, y:14}));");

Console output:
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at System.IO.TextWriter.WriteLine(String format, Object[] arg)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(String format, Object[] arg)
   at System.Console.WriteLine(String format, Object[] arg)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Jint.Runtime.Interop.MethodInfoFunctionInstance.Invoke(MethodInfo[] methodInfos, JsValue thisObject, JsValue[] jsArguments)
   at Jint.Runtime.Interop.MethodInfoFunctionInstance.Call(JsValue thisObject, JsValue[] arguments)
   at Jint.Runtime.ExpressionInterpreter.EvaluateCallExpression(CallExpression callExpression)
   at Jint.Engine.EvaluateExpression(Expression expression)
   at Jint.Runtime.StatementInterpreter.ExecuteExpressionStatement(ExpressionStatement expressionStatement)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Runtime.StatementInterpreter.ExecuteStatementList(IEnumerable`1 statementList)
   at Jint.Engine.Execute(Program program)
   at Jint.Engine.Execute(String source)

**Comment by nilsmoh** [comment]
Explicitly giving a format string fixes the problem - so there must be something wrong with arity autodetection(?!)
This works:
this.engine.Execute("System.Console.WriteLine('{0}',JSON.stringify({x:12, y:14}));");

**Comment by pranayrauthu** [comment]
I would suggest setting Console.Writeline function in the engine as a variable and use it in the script.


```csharp
var engine = new Engine();
engine.SetValue("log", new Action<string>(System.Console.WriteLine));
engine.Execute(@"
    log(JSON.stringify({x:12, y:14}));
");
```
