### ISSUE TITLE
Why don't the Errors have stacks?

### ISSUE THREAD

**Issue by djMax** [sebastienros/jint#293]
If this is just an oversight, I'll set about trying to correct it... But I wondered if there was some reason the javascript errors don't generate stacks? this simple test results in no stack on the created error (was trying to check on location handling as well)...

```
function start() {
  second();
}

function second() {
  third();
}

function third() {
  throw new Error('WTF');
}

start();
```

**Comment by djMax** [comment]
I've got code now that will produce this (from source file polyfill.pack.js):
```
Error: WTF
	at third (polyfill.pack.js:10:30)
	at second (polyfill.pack.js:6:2)
	at start (polyfill.pack.js:2:2)
	at <global> (polyfill.pack.js:13:0)
```

**Comment by djMax** [comment]
#297
