### ISSUE TITLE
Jint Engine throws System.ArgumentException: An item with the same key has already been added

### ISSUE THREAD

**Issue by yogidev** [sebastienros/jint#384]
I am working on ASP.NET MVC app which uses Jint to read JSON files having validations rules in javascript.

For ex. m.IsoCode === 'BAN' or ['USA','BRN'].indexOf(m.CountryId) > -1 where 'm' is the model which contains data.

we use below code to read and execute the rules defined in json files.The variable 'rule' contains java script expression and model contains the data.

```
public class RuleEngine
        {
            private Engine _engine;

            public RuleEngine()
            {
                _engine = new Engine();
            }

            public bool EvaluateJSExpression(object rule, T model)
            {            
                bool returnVal = true;

                try
                {
                    _engine.SetValue("m", model).Execute(rule.ToString());
                    var completionObj = _engine.GetCompletionValue();

                    if (!completionObj.IsUndefined())
                    {
                        returnVal = (bool)completionObj.ToObject();
                    }
                    else
                    {
                         throw new FormatException("The rule format is incorrect:" + 
                         rule.ToString());
                    }
                }
                catch(Exception ex)
                {
                    throw new FormatException("The following rule did not execute:" 
                   + rule.ToString(), ex);
                }

                return returnVal;

            }
     }
When we do concurrent users load testing, we get below error call stack :

**System.ArgumentException: An item with the same key has already been added.
at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Jint.Runtime.Interop.ObjectWrapper.GetOwnProperty(String propertyName)**
   at Jint.Native.Object.ObjectInstance.GetProperty(String propertyName)
   at Jint.Native.Object.ObjectInstance.Get(String propertyName)
   at Jint.Engine.GetValue(Object value)
   at Jint.Runtime.ExpressionInterpreter.EvaluateBinaryExpression(BinaryExpression expression)
   at Jint.Engine.EvaluateExpression(Expression expression)
   at Jint.Runtime.StatementInterpreter.ExecuteExpressionStatement(ExpressionStatement expressionStatement)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Runtime.StatementInterpreter.ExecuteStatementList(IEnumerable`1 statementList)
   at Jint.Engine.Execute(Program program)

```
**System.ArgumentException: An item with the same key has already been added.
at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
at Jint.Runtime.Interop.ObjectWrapper.GetOwnProperty(String propertyName)**

I find out an issue in this forum:  https://github.com/sebastienros/jint/issues/320 Program object is not thread-safe. Is this issue applicable in my code?

I am using Jint ver. 2.8. Kindly let me know how to fix this issue? The Dictionary used in Jint for Properties (MruPropertyCache2) is thread-safe?

Thanks in advance.

**Comment by sebastienros** [comment]
An engine instance is not thread safe, each request in your case needs a new instance. What you can share across threads is a `Program` instance in case you want to cache the parsing phase.

**Comment by sebastienros** [comment]
In your case (RuleEngine class) you should instantiate Engine in the `EvaluateJSExpression` method.
