### ISSUE TITLE
UWP Enum reference results in System.InvalidCastException: Object must implement IConvertible.

### ISSUE THREAD

**Issue by mtinnes** [sebastienros/jint#416]
We are trying to implement Jint in a UWP app and have come across an issue when referencing an Enum from the Windows.UI.Xaml namespace. Specifically we are trying to call `ItemSelection.Visibility = Windows.UI.Xaml.Visibility.Collapsed;` and are getting the following exception:
```

System.InvalidCastException: Object must implement IConvertible.
   at System.Linq.Expressions.Interpreter.MethodInfoCallInstruction.InvokeWorker(Object[] args)
   at System.Linq.Expressions.Interpreter.MethodInfoCallInstruction.Run(InterpretedFrame frame)
   at System.Linq.Expressions.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Linq.Expressions.Interpreter.LightLambda.RunVoid(Object[] arguments)
   at System.Linq.Expressions.Interpreter.MethodInfoCallInstruction.InvokeWorker(Object[] args)
   at System.Linq.Expressions.Interpreter.MethodInfoCallInstruction.Run(InterpretedFrame frame)
   at System.Linq.Expressions.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Linq.Expressions.Interpreter.LightLambda.RunVoid(Object[] arguments)
   at Thunk(Func`2 , Object , EventArgs )
```

We are using `cfg.AllowClr()` on the engine, is there anything in particular about Enums that need special attention?

**Comment by sebastienros** [comment]
There shouldn't be anything special, it there a way for you to reference the source and see what is failing? Or maybe create a unit test that fails?

**Comment by mtinnes** [comment]
I should also mention we are using 2.10.4. After the update to latest we ran into portability issues with ARM platform targets and had to revert. When you say reference the source, are you saying determine where in the Jint source the problem is originating? Unit testing may be difficult since we are referencing live components in the UWP app.

**Comment by lahma** [comment]
Closing as obsolete. If further improvements needed with 3.x version please create a PR.
