### ISSUE TITLE
Object creation fails with message "Unexpected token :"

### ISSUE THREAD

**Issue by Ghostbird** [sebastienros/jint#437]
When I try to execute this C# string:
```C#
new Engine().Execute(@"{
    MyItem  : 1,
    MyColor : 'red',
    MySize  : true,
    MyCount : null
}").GetCompletionValue().ToObject();
```
I get this error:
```stacktrace
Error Message:
 Esprima.ParserException : Line 3': Unexpected token :
Stack Trace:
   at Esprima.JavaScriptParser.ThrowUnexpectedToken(Token token, String message)
   at Esprima.JavaScriptParser.ConsumeSemicolon()
   at Esprima.JavaScriptParser.ParseExpressionStatement()
   at Esprima.JavaScriptParser.ParseStatement()
   at Esprima.JavaScriptParser.ParseLabelledStatement()
   at Esprima.JavaScriptParser.ParseStatement()
   at Esprima.JavaScriptParser.ParseStatementListItem()
   at Esprima.JavaScriptParser.ParseBlock()
   at Esprima.JavaScriptParser.ParseStatement()
   at Esprima.JavaScriptParser.ParseStatementListItem()
   at Esprima.JavaScriptParser.ParseProgram(Boolean strict)
   at Jint.Engine.Execute(String source, ParserOptions parserOptions)
```
I expected to get a new object in return. Is this a bug? Or did I do something wrong?
Note that this works fine:
```C#
new Engine().Execute(@"var obj = {
    MyItem  : 1,
    MyColor : 'red',
    MySize  : true,
    MyCount : null
};
obj;").GetCompletionValue().ToObject();
```
This returns the object as expected. It seems Esprima fails to parse the Javascript object literal under some circumstances.

**Comment by sebastienros** [comment]
Looks like a Statement can't be an object declaration directly. Either because the specification states so, or because of a bug in Esprima.NET. Can you check what the spec says?

**Comment by sebastienros** [comment]
I see, actually it thinks it's a Labelled statement. It enters a block ( `{` } then sees `MyItem: 1` which is a label construct. Because we are interpreting a program in this case. That would work if you called `ParseObjectExpression` directly, assuming that's the actual purpose.

**Comment by Ghostbird** [comment]
Ah, the parser can't distinguish between a block statement and an object literal in this case, without lookahead parsing. Makes perfect sense in retrospect.
