### ISSUE TITLE
The value is not a string

### ISSUE THREAD

**Issue by kane-mason** [sebastienros/jint#489]
Hi, 

This parser has been working great for me up until recently. I get the following exception thrown as i perform an Engine.Execute(js). Everything was working fine in 3.0.0-beta-001, and the trouble started from 3.0.0-beta-1101

System.ArgumentException
  HResult=0x80070057
  Message=The value is not a string
  Source=JSParser
  StackTrace:
   at JSParser.JSFunctions.getEngine(String game, String version) in C:\server.JsParser\JSTestCore2.0\ParseFunctions.cs:line 92
   at JSParser.JSFunctions.Invoke(String game, String version, String function, Object[] arguments) in C:\server.JsParser\JSTestCore2.0\ParseFunctions.cs:line 41
   at JSParser.JSFunctions.InitGame(String game, String version, Object[] arguments) in C:\server.JsParser\JSTestCore2.0\ParseFunctions.cs:line 23
   at ServerToJSParserUnitTests.JSTests.InitGameTestFunction() in C:\server.JsParser\ServerToJSParserUnitTests\JSTests.cs:line 44

**Comment by sebastienros** [comment]
We'll need more information than that, like how you are calling it and what are the arguments.
There is nothing in this stack trace that shows when Jint is used.

**Comment by kane-mason** [comment]
Here is a code snippet of useage. Error occurs at Execute. Can i email or privately message the javascript?

                engine = new Engine();

                if (JSFunctions.debug == true)
                {
                    engine.SetValue("log", new Action<object>(Console.WriteLine));
                }

                String js = System.IO.File.ReadAllText(filePath);

                try
                {
                    engine.Execute(js);
                }
                catch (Exception ex)
                {
                    Console.WriteLine("ERROR: " + ex.Message);

                    if (ex is Jint.Runtime.JavaScriptException)
                    {
                        var jse = (Jint.Runtime.JavaScriptException)ex;
                        Console.WriteLine("JAVASCRIPT RUNTIME EXCEPTION");
                        Console.WriteLine("LINE: " + jse.LineNumber);
                        Console.WriteLine("COLUMN: " + jse.Column);
                    }

                    throw ex;

                }

**Comment by lahma** [comment]
Closing due to inactivity. Should probably try out 3.x series from NuGet which has fixes and new features. We can reopen if more information appears to reproduce.
