### ISSUE TITLE
NullReferenceException in IIFE when limiting recursion

### ISSUE THREAD

**Issue by Taritsyn** [sebastienros/jint#707]
Hello!

In Jint version Beta 1715 when restricting recursion by using the `LimitRecursion` option in the immediately invoked function expression started to throw an null reference exception:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jint.Runtime.Interpreter.Expressions.JintCallExpression.EvaluateInternal()
   at Jint.Runtime.Interpreter.Expressions.JintExpression.GetValue()
   at Jint.Runtime.Interpreter.Statements.JintExpressionStatement.ExecuteInternal()
   at Jint.Runtime.Interpreter.JintStatementList.Execute()
   at Jint.Engine.Execute(Program program)
   at Jint.Engine.Execute(String source, ParserOptions parserOptions)
   at Jint.Engine.Execute(String source)
```

To reproduce this error, I created a example:

```csharp
using System;

using Jint;
using Jint.Runtime;

namespace TestJint
{
    class Program
    {
        static void Main(string[] args)
        {
            const string input = @"(function () {
                var factorial = function(n) {
                    if (n>1) {
                        return n * factorial(n - 1);
                    }
                };

                var result = factorial(38);
            })();
            ";

            try
            {
                var engine = new Engine(o => o.LimitRecursion(20));
                engine.Execute(input);
            }
            catch (RecursionDepthOverflowException)
            {
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("Success!");
            }
            catch (Exception e)
            {
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("Failed!");

                Console.WriteLine();

                Console.ForegroundColor = ConsoleColor.White;
                Console.WriteLine(e.ToString());
            }

            Console.ForegroundColor = ConsoleColor.White;
        }
    }
}
```

**Comment by ashepetko** [comment]
Experiencing the same issue. The following line lacks null propagation before the call to `ToString()`:
https://github.com/sebastienros/jint/blob/6e92af9a761d2137c8587a00248bf4a38919a30b/Jint/Runtime/Interpreter/Expressions/JintCallExpression.cs#L115

Same potential issue here:
https://github.com/sebastienros/jint/blob/6e92af9a761d2137c8587a00248bf4a38919a30b/Jint/Runtime/ExceptionHelper.cs#L40

**Comment by ashepetko** [comment]
Pull request with the fix #708

**Comment by lahma** [comment]
Thank you @Taritsyn for reporting!. As noted, a PR has been prepared containing the fix and the test case you provided.

**Comment by Taritsyn** [comment]
Thanks!
