### ISSUE TITLE
Issue with date value parsing in different time-zones

### ISSUE THREAD

**Issue by koolkicks88** [sebastienros/jint#787]
Good day, 

I ran into an issue while loading a javascript library to take care of the parsing and formatting for different date values. It seems that problem arises when a user is in a timezone of UTC +1 and on (For example, Europe/Paris), but we don't see the same behavior if we use a timezone that is valid in the United States (my timezone is UTC -06:00 Central Time). 

Below is how I load 3 separate JS libraries into Jint:

`_jsEngine = new Engine().Execute(_momentJs).Execute(_momentLocale).Execute(_momentJsTz);`
 I have also tried loading them one at a time. 

The 3 separate js libraries contain separate logic for momentJs, one of then includes information for the locale, and the other one contains information for timezones (more information on the js libraries will be posted below). 

The issue I am running into is that when the user is in a UTC +1 timezone and runs the following function (the date format I am attempting to parse is "yyyy"):
`var parsedDate = _jsEngine.Execute($"\nmoment().format(\"{dateFormat}\")")
                    .GetCompletionValue()
                    .ToString();`
The following error message appears: "Year, Month, and Day parameters describe an un-representable DateTime."
The stack trace shows the following:
```   
   at System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day)
   at Jint.Native.Date.DatePrototype.DaylightSavingTa(Double t)
   at Jint.Native.Date.DatePrototype.Utc(Double t)
   at Jint.Native.Date.DatePrototype.SetFullYear(JsValue thisObj, JsValue[] arguments)
   at Jint.Runtime.Interop.ClrFunctionInstance.Call(JsValue thisObject, JsValue[] arguments)
   at Jint.Runtime.ExpressionInterpreter.EvaluateCallExpression(CallExpression callExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateLogicalExpression(LogicalExpression logicalExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateSequenceExpression(SequenceExpression sequenceExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateConditionalExpression(ConditionalExpression conditionalExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateSequenceExpression(SequenceExpression sequenceExpression)
   at Jint.Runtime.StatementInterpreter.ExecuteReturnStatement(ReturnStatement statement)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Runtime.StatementInterpreter.ExecuteStatementList(IEnumerable`1 statementList)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Native.Function.ScriptFunctionInstance.Call(JsValue thisArg, JsValue[] arguments)
   at Jint.Native.Function.FunctionPrototype.Apply(JsValue thisObject, JsValue[] arguments)
   at Jint.Runtime.Interop.ClrFunctionInstance.Call(JsValue thisObject, JsValue[] arguments)
   at Jint.Runtime.ExpressionInterpreter.EvaluateCallExpression(CallExpression callExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateAssignmentExpression(AssignmentExpression assignmentExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateSequenceExpression(SequenceExpression sequenceExpression)
   at Jint.Runtime.StatementInterpreter.ExecuteExpressionStatement(ExpressionStatement expressionStatement)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Runtime.StatementInterpreter.ExecuteStatementList(IEnumerable`1 statementList)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Runtime.StatementInterpreter.ExecuteIfStatement(IfStatement ifStatement)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Runtime.StatementInterpreter.ExecuteStatementList(IEnumerable`1 statementList)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Native.Function.ScriptFunctionInstance.Call(JsValue thisArg, JsValue[] arguments)
   at Jint.Runtime.ExpressionInterpreter.EvaluateCallExpression(CallExpression callExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateSequenceExpression(SequenceExpression sequenceExpression)
   at Jint.Runtime.StatementInterpreter.ExecuteExpressionStatement(ExpressionStatement expressionStatement)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Runtime.StatementInterpreter.ExecuteStatementList(IEnumerable`1 statementList)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Runtime.StatementInterpreter.ExecuteIfStatement(IfStatement ifStatement)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Runtime.StatementInterpreter.ExecuteIfStatement(IfStatement ifStatement)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Runtime.StatementInterpreter.ExecuteStatementList(IEnumerable`1 statementList)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Native.Function.ScriptFunctionInstance.Call(JsValue thisArg, JsValue[] arguments)
   at Jint.Runtime.ExpressionInterpreter.EvaluateCallExpression(CallExpression callExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateSequenceExpression(SequenceExpression sequenceExpression)
   at Jint.Runtime.StatementInterpreter.ExecuteExpressionStatement(ExpressionStatement expressionStatement)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Runtime.StatementInterpreter.ExecuteStatementList(IEnumerable`1 statementList)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Runtime.StatementInterpreter.ExecuteIfStatement(IfStatement ifStatement)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Runtime.StatementInterpreter.ExecuteStatementList(IEnumerable`1 statementList)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Native.Function.ScriptFunctionInstance.Call(JsValue thisArg, JsValue[] arguments)
   at Jint.Runtime.ExpressionInterpreter.EvaluateCallExpression(CallExpression callExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateSequenceExpression(SequenceExpression sequenceExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateConditionalExpression(ConditionalExpression conditionalExpression)
   at Jint.Runtime.StatementInterpreter.ExecuteExpressionStatement(ExpressionStatement expressionStatement)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Runtime.StatementInterpreter.ExecuteStatementList(IEnumerable`1 statementList)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Native.Function.ScriptFunctionInstance.Call(JsValue thisArg, JsValue[] arguments)
   at Jint.Runtime.ExpressionInterpreter.EvaluateCallExpression(CallExpression callExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateConditionalExpression(ConditionalExpression conditionalExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateConditionalExpression(ConditionalExpression conditionalExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateConditionalExpression(ConditionalExpression conditionalExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateConditionalExpression(ConditionalExpression conditionalExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateConditionalExpression(ConditionalExpression conditionalExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateConditionalExpression(ConditionalExpression conditionalExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateSequenceExpression(SequenceExpression sequenceExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateConditionalExpression(ConditionalExpression conditionalExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateSequenceExpression(SequenceExpression sequenceExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateConditionalExpression(ConditionalExpression conditionalExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateSequenceExpression(SequenceExpression sequenceExpression)
   at Jint.Runtime.StatementInterpreter.ExecuteReturnStatement(ReturnStatement statement)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Runtime.StatementInterpreter.ExecuteStatementList(IEnumerable`1 statementList)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Native.Function.ScriptFunctionInstance.Call(JsValue thisArg, JsValue[] arguments)
   at Jint.Runtime.ExpressionInterpreter.EvaluateCallExpression(CallExpression callExpression)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at Jint.Runtime.ExpressionInterpreter.EvaluateCallExpression(CallExpression callExpression)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at Jint.Runtime.ExpressionInterpreter.EvaluateNewExpression(NewExpression newExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateAssignmentExpression(AssignmentExpression assignmentExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateMemberExpression(MemberExpression memberExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateLogicalExpression(LogicalExpression logicalExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateSequenceExpression(SequenceExpression sequenceExpression)
   at Jint.Runtime.StatementInterpreter.ExecuteReturnStatement(ReturnStatement statement)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Runtime.StatementInterpreter.ExecuteStatementList(IEnumerable`1 statementList)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Native.Function.ScriptFunctionInstance.Call(JsValue thisArg, JsValue[] arguments)
   at Jint.Runtime.ExpressionInterpreter.EvaluateCallExpression(CallExpression callExpression)
   at Jint.Runtime.StatementInterpreter.ExecuteReturnStatement(ReturnStatement statement)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Runtime.StatementInterpreter.ExecuteStatementList(IEnumerable`1 statementList)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Native.Function.ScriptFunctionInstance.Call(JsValue thisArg, JsValue[] arguments)
   at Jint.Native.Function.FunctionPrototype.Apply(JsValue thisObject, JsValue[] arguments)
   at Jint.Runtime.Interop.ClrFunctionInstance.Call(JsValue thisObject, JsValue[] arguments)
   at Jint.Runtime.ExpressionInterpreter.EvaluateCallExpression(CallExpression callExpression)
   at Jint.Runtime.StatementInterpreter.ExecuteReturnStatement(ReturnStatement statement)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Runtime.StatementInterpreter.ExecuteStatementList(IEnumerable`1 statementList)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Native.Function.ScriptFunctionInstance.Call(JsValue thisArg, JsValue[] arguments)
   at Jint.Runtime.ExpressionInterpreter.EvaluateCallExpression(CallExpression callExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateMemberExpression(MemberExpression memberExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateCallExpression(CallExpression callExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateAssignmentExpression(AssignmentExpression assignmentExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateSequenceExpression(SequenceExpression sequenceExpression)
   at Jint.Runtime.StatementInterpreter.ExecuteExpressionStatement(ExpressionStatement expressionStatement)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Runtime.StatementInterpreter.ExecuteStatementList(IEnumerable`1 statementList)
   at Jint.Runtime.StatementInterpreter.ExecuteSwitchBlock(IEnumerable`1 switchBlock, JsValue input)
   at Jint.Runtime.StatementInterpreter.ExecuteSwitchStatement(SwitchStatement switchStatement)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Runtime.StatementInterpreter.ExecuteStatementList(IEnumerable`1 statementList)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Runtime.StatementInterpreter.ExecuteForStatement(ForStatement forStatement)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Runtime.StatementInterpreter.ExecuteStatementList(IEnumerable`1 statementList)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Native.Function.ScriptFunctionInstance.Call(JsValue thisArg, JsValue[] arguments)
   at Jint.Runtime.ExpressionInterpreter.EvaluateCallExpression(CallExpression callExpression)
   at Jint.Runtime.StatementInterpreter.ExecuteVariableDeclaration(VariableDeclaration statement)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Runtime.StatementInterpreter.ExecuteForStatement(ForStatement forStatement)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Runtime.StatementInterpreter.ExecuteStatementList(IEnumerable`1 statementList)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Native.Function.ScriptFunctionInstance.Call(JsValue thisArg, JsValue[] arguments)
   at Jint.Runtime.ExpressionInterpreter.EvaluateCallExpression(CallExpression callExpression)
   at Jint.Runtime.StatementInterpreter.ExecuteReturnStatement(ReturnStatement statement)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Runtime.StatementInterpreter.ExecuteStatementList(IEnumerable`1 statementList)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Native.Function.ScriptFunctionInstance.Call(JsValue thisArg, JsValue[] arguments)
   at Jint.Runtime.Interop.ClrFunctionInstance.Call(JsValue thisObject, JsValue[] arguments)
   at Jint.Runtime.ExpressionInterpreter.EvaluateCallExpression(CallExpression callExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateConditionalExpression(ConditionalExpression conditionalExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateAssignmentExpression(AssignmentExpression assignmentExpression)
   at Jint.Runtime.StatementInterpreter.ExecuteExpressionStatement(ExpressionStatement expressionStatement)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Runtime.StatementInterpreter.ExecuteForStatement(ForStatement forStatement)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Runtime.StatementInterpreter.ExecuteStatementList(IEnumerable`1 statementList)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Native.Function.ScriptFunctionInstance.Call(JsValue thisArg, JsValue[] arguments)
   at Jint.Runtime.ExpressionInterpreter.EvaluateCallExpression(CallExpression callExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateSequenceExpression(SequenceExpression sequenceExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateConditionalExpression(ConditionalExpression conditionalExpression)
   at Jint.Runtime.StatementInterpreter.ExecuteReturnStatement(ReturnStatement statement)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Runtime.StatementInterpreter.ExecuteStatementList(IEnumerable`1 statementList)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Native.Function.ScriptFunctionInstance.Call(JsValue thisArg, JsValue[] arguments)
   at Jint.Runtime.ExpressionInterpreter.EvaluateCallExpression(CallExpression callExpression)
   at Jint.Runtime.StatementInterpreter.ExecuteVariableDeclaration(VariableDeclaration statement)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Runtime.StatementInterpreter.ExecuteStatementList(IEnumerable`1 statementList)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Native.Function.ScriptFunctionInstance.Call(JsValue thisArg, JsValue[] arguments)
   at Jint.Runtime.ExpressionInterpreter.EvaluateCallExpression(CallExpression callExpression)
   at Jint.Runtime.StatementInterpreter.ExecuteExpressionStatement(ExpressionStatement expressionStatement)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Runtime.StatementInterpreter.ExecuteStatementList(IEnumerable`1 statementList)
   at Jint.Runtime.StatementInterpreter.ExecuteProgram(Program program)
   at Jint.Engine.Execute(Program program)
   at Jint.Engine.Execute(String source)
   at JintSample.Program.FormatDate(String regEx, String date) in C:\Users\m\Desktop\M\Jint\JintSample\Program.cs:line 168
   at JintSample.Program.Main(String[] args) in C:\Users\m\Desktop\M\Jint\JintSample\Program.cs:line 45
```

When a user runs the same function and it is in a central timezone (UTC -06:00), it works without an issue.

We have a reason to think that something is going on inside the SetFullYear method, but that is as far as we got. We would like to know if there are available solutions to this issue? Please let me know if I can provide more information.
Thanks

Note: For more information in regards to the libraries check out the following link: https://momentjs.com/

**Comment by pinonpierre** [comment]
Hi,

I have the same issue :)

**Comment by lahma** [comment]
Adding note that #778 might be related to this same date handling.

**Comment by lahma** [comment]
This has now hopefully be fixed in main and soon available on MyGet feed.
