### ISSUE TITLE
Cannot access child value on Newtonsoft.Json.Linq.JValue in OrchardCore

### ISSUE THREAD

**Issue by jptissot** [sebastienros/jint#795]
```
An unhandled exception has occurred while executing the request.
System.InvalidOperationException: Cannot access child value on Newtonsoft.Json.Linq.JValue.
   at Jint.Runtime.Descriptors.Specialized.IndexDescriptor.get_CustomValue()
   at Jint.Native.Object.ObjectInstance.UnwrapJsValue(PropertyDescriptor desc, JsValue thisObject)
   at Jint.Native.Object.ObjectInstance.Get(JsValue property, JsValue receiver)
   at Jint.Runtime.TypeConverter.OrdinaryToPrimitive(ObjectInstance input, Types hint)
   at Jint.Runtime.TypeConverter.ToPrimitive(JsValue input, Types preferredType)
   at Jint.Runtime.Interpreter.Expressions.JintExpression.EqualUnlikely(JsValue x, JsValue y)
   at Jint.Runtime.Interpreter.Expressions.JintExpression.Equal(JsValue x, JsValue y)
   at Jint.Runtime.Interpreter.Expressions.JintBinaryExpression.EqualBinaryExpression.EvaluateInternal()
   at Jint.Runtime.Interpreter.Expressions.JintBinaryExpression.GetValue()
   at Jint.Runtime.Interpreter.Statements.JintIfStatement.ExecuteInternal()
   at Jint.Runtime.Interpreter.JintStatementList.Execute()
   at Jint.Engine.Execute(Script program)
   at OrchardCore.Scripting.JavaScript.JavaScriptEngine.Evaluate(IScriptingScope scope, String script) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Scripting.JavaScript\JavaScriptEngine.cs:line 47
   at OrchardCore.Scripting.DefaultScriptingManager.Evaluate(String directive, IFileProvider fileProvider, String basePath, IEnumerable`1 scopedMethodProviders) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Infrastructure\Scripting\DefaultScriptingManager.cs:line 45

```

See https://github.com/OrchardCMS/OrchardCore/issues/7452
and https://github.com/OrchardCMS/OrchardCore/pull/7485

**Comment by lahma** [comment]
I had a quick look and I think this might be the reason:

https://github.com/sebastienros/jint/commit/0f2c39b912ef7d91d4e804897c7d540d173b83e0#diff-cb9f1edd4924c5cce48293a371cbf0f53cfec3693d40c0657c7264f7e1b4b40dL100-L103

We used to swallow this kind of exception and just return Undefined. So probably wasn't working correctly before, now just manifesting the the error.
