### ISSUE TITLE
InvalidOperationException during a recursive call of engine

### ISSUE THREAD

**Issue by Taritsyn** [sebastienros/jint#835]
Hello!

In Jint version Beta 2002 during a recursive call of engine the following exception is thrown:

```
System.InvalidOperationException: stack is empty
   at Jint.Runtime.ExceptionHelper.ThrowInvalidOperationException(String message)
   at Jint.Runtime.CallStack.JintCallStack.Pop()
   at Jint.Engine.Call(FunctionInstance functionInstance, JsValue thisObject, JsValue[] arguments, JintExpression expression)
   at Jint.Engine.Call(ICallable callable, JsValue thisObject, JsValue[] arguments, JintExpression expression)
   at Jint.Runtime.Interpreter.Expressions.JintCallExpression.Call()
   at Jint.Runtime.Interpreter.Expressions.JintCallExpression.EvaluateInternal()
   at Jint.Runtime.Interpreter.Expressions.JintExpression.GetValue()
   at Jint.Runtime.Interpreter.Statements.JintExpressionStatement.ExecuteInternal()
   at Jint.Runtime.Interpreter.JintStatementList.Execute()
   at Jint.Engine.Execute(Script script, Boolean resetState)
   at Jint.Engine.Execute(Script script)
   at Jint.Engine.Execute(String source, ParserOptions parserOptions)
   at Jint.Engine.Execute(String source)
   at TestJint.Program.Main(String[] args) in C:\Temp\TestJint\TestJint\Program.cs:line 26
```

There were no such errors in version Beta 1914.  To reproduce this error, I created a example:

```csharp
using System;

using Jint;
using Jint.Native;
using Jint.Runtime;

namespace TestJint
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                var engine = new Engine();
                Func<string, object> evaluateCode = code => {
                    return engine.Execute(code)
                        .GetCompletionValue()
                        ;
                };
                JsValue evaluateCodeValue = JsValue.FromObject(engine, evaluateCode);

                engine.SetValue("evaluateCode", evaluateCodeValue);
                int result = (int)engine.Execute(@"evaluateCode('678 + 711')")
                    .GetCompletionValue()
                    .AsNumber()
                    ;

                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("Success!");

                Console.WriteLine();

                Console.ForegroundColor = ConsoleColor.White;
                Console.WriteLine("Result: {0}", result);
            }
            catch (Exception e)
            {
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("Failed!");

                Console.WriteLine();

                Console.ForegroundColor = ConsoleColor.White;
                Console.WriteLine(e.ToString());
            }
        }
    }
}
```

In fact, I use [more complex code](https://github.com/Taritsyn/JavaScriptEngineSwitcher/blob/4fdc03abe5afbfd91d65d255ed2433ab3c4d424b/test/JavaScriptEngineSwitcher.Tests/InteropTestsBase.cs#L663-L690) in my tests.

**Comment by lahma** [comment]
Thank you @Taritsyn for reporting (both) issues! I'll try to dig in to them soon,  great to have clear reproduction available.

**Comment by Taritsyn** [comment]
Thanks!
